### ISSUE TITLE
Add RouteEnhancers example to documentation

### ISSUE THREAD

**Issue by co-operate** [bithost-gmbh/pdfviewhelpers#126]
Struggling with getting the type parameter to show up in URLs in TYPO3 v9.5

**Comment by maechler** [comment]
@co-operate Could you please tell us more about your specific use case? 
The page type parameter is not needed in most cases.

If you wanted to be able to render each page also as PDF, I guess you could do something like this (not tested!):

```yaml
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: '/'
    map:
      .pdf: 1234
```
